Импортируем библиотеки, которые нам понадобятся (pandas для работы с данными, numpy для математических преобразований, matplotlib и seaborn для визуализации):

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Прочитаем наши данные и выведем первые пять строк таблицы с помощью head(), чтобы убедиться в том, что всё подгрузилось верно

In [3]:
sber_data = pd.read_csv('data/sber_data.csv')
sber_data.head()

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,...,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,mosque_count_1000,price_doc
0,1,43,27.0,4.0,Bibirevo,5001.0,5,11065.0,5,0,...,0.637189,0.947962,0.177975,0.625783,0.628187,14.053047,7.389498,good,0,5850000
1,2,34,19.0,3.0,Nagatinskij Zaton,3119.0,5,6237.0,8,0,...,0.688796,1.072315,0.273345,0.967821,0.471447,6.829889,0.709260,excellent,0,6000000
2,3,43,29.0,2.0,Tekstil'shhiki,1463.0,4,5580.0,7,0,...,1.543049,0.391957,0.158072,3.178751,0.755946,4.273200,3.156423,poor,0,5700000
3,4,89,50.0,9.0,Mitino,6839.0,9,17063.0,10,0,...,0.934273,0.892674,0.236455,1.031777,1.561505,16.990677,16.041521,good,0,13100000
4,5,77,77.0,4.0,Basmannoe,3240.0,7,7770.0,9,0,...,0.077901,0.810801,0.376838,0.378756,0.121681,1.112486,1.800125,excellent,0,16331452

Дополнительно посмотрим на последние пять строк таблицы с помощью tail()

In [4]:
display(sber_data.tail())

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,...,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,mosque_count_1000,price_doc
30466,30469,44,27.0,7.0,Otradnoe,5088.0,4,12721.0,4,0,...,1.103579,0.167718,0.349899,1.235066,0.612359,7.482165,4.836787,good,0,7400000
30467,30470,86,59.0,3.0,Tverskoe,1874.0,4,6772.0,4,1,...,0.069986,0.086552,0.362681,0.850385,0.310021,0.778428,1.450108,poor,0,25000000
30468,30471,45,NaN,10.0,Poselenie Vnukovskoe,NaN,0,NaN,0,0,...,4.338453,1.339078,1.234235,1.192543,1.186621,13.459593,9.890758,no data,0,6970959
30469,30472,64,32.0,5.0,Obruchevskoe,2372.0,6,6083.0,8,0,...,1.204798,1.340017,0.130667,1.644053,0.476021,2.088193,4.119706,satisfactory,0,13500000
30470,30473,43,28.0,1.0,Novogireevo,2215.0,4,5824.0,4,0,...,2.108265,0.825811,0.378950,0.480531,0.867332,0.688707,0.127867,poor,0,5600000

In [22]:
display(sber_data.info(max_cols = 61))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30471 entries, 0 to 30470
Data columns (total 61 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     30471 non-null  int64
 1   full_sq                                30471 non-null  int64
 2   life_sq                                24088 non-null  float64
 3   floor                                  30304 non-null  float64
 4   sub_area                               30471 non-null  object
 5   preschool_quota                        23783 non-null  float64
 6   preschool_education_centers_raion      30471 non-null  int64
 7   school_quota                           23786 non-null  float64
 8   school_education_centers_raion         30471 non-null  int64
 9   school_education_centers_top_20_raion  30471 non-null  int64
 10  hospital_beds_raion                    16030 non-null  float64
 11  healthcare_centers_raion               30471 non-null  int64
 12  university_top_20_raion                30471 non-null  int64
 13  sport_objects_raion                    30471 non-null  int64
 14  additional_education_raion             30471 non-null  int64
 15  culture_objects_top_25_raion           30471 non-null  int64
 16  shopping_centers_raion                 30471 non-null  int64
 17  office_raion                           30471 non-null  int64
 18  oil_chemistry_raion                    30471 non-null  object
 19  railroad_terminal_raion                30471 non-null  object
 20  nuclear_reactor_raion                  30471 non-null  object
 21  metro_min_avto                         30471 non-null  float64
 22  metro_km_avto                          30471 non-null  float64
 23  metro_min_walk                         30446 non-null  float64
 24  metro_km_walk                          30446 non-null  float64
 25  kindergarten_km                        30471 non-null  float64
 26  school_km                              30471 non-null  float64
 27  park_km                                30471 non-null  float64
 28  green_zone_km                          30471 non-null  float64
 29  industrial_km                          30471 non-null  float64
 30  railroad_station_walk_km               30446 non-null  float64
 31  railroad_station_walk_min              30446 non-null  float64
 32  public_transport_station_km            30471 non-null  float64
 33  public_transport_station_min_walk      30471 non-null  float64
 34  mkad_km                                30471 non-null  float64
 35  ttk_km                                 30471 non-null  float64
 36  sadovoe_km                             30471 non-null  float64
 37  bulvar_ring_km                         30471 non-null  float64
 38  kremlin_km                             30471 non-null  float64
 39  big_road1_1line                        30471 non-null  object
 40  big_market_km                          30471 non-null  float64
 41  market_shop_km                         30471 non-null  float64
 42  fitness_km                             30471 non-null  float64
 43  swim_pool_km                           30471 non-null  float64
 44  ice_rink_km                            30471 non-null  float64
 45  stadium_km                             30471 non-null  float64
 46  basketball_km                          30471 non-null  float64
 47  hospice_morgue_km                      30471 non-null  float64
 48  university_km                          30471 non-null  float64
 49  workplaces_km                          30471 non-null  float64
 50  shopping_centers_km                    30471 non-null  float64
 51  office_km                              30471 non-null  float64
 52  additional_education_km                30471 non-null  float64
 53  preschool_km                           30471 non-null  float64
 54  big_church_km                          30471 non-null  float64
 55  church_synagogue_km                    30471 non-null  float64
 56  theater_km                             30471 non-null  float64
 57  museum_km                              30471 non-null  float64
 58  ecology                                30471 non-null  object
 59  mosque_count_1000                      30471 non-null  int64
 60  price_doc                              30471 non-null  int64
dtypes: float64(41), int64(14), object(6)
memory usage: 14.2+ MB

None

Отобразим все колнки

In [ ]:

pd.set_option("display.max_columns",61)
display(sber_data)

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,hospital_beds_raion,healthcare_centers_raion,university_top_20_raion,sport_objects_raion,additional_education_raion,culture_objects_top_25_raion,shopping_centers_raion,office_raion,oil_chemistry_raion,railroad_terminal_raion,nuclear_reactor_raion,metro_min_avto,metro_km_avto,metro_min_walk,metro_km_walk,kindergarten_km,school_km,park_km,green_zone_km,industrial_km,railroad_station_walk_km,railroad_station_walk_min,public_transport_station_km,public_transport_station_min_walk,mkad_km,ttk_km,sadovoe_km,bulvar_ring_km,kremlin_km,big_road1_1line,big_market_km,market_shop_km,fitness_km,swim_pool_km,ice_rink_km,stadium_km,basketball_km,hospice_morgue_km,university_km,workplaces_km,shopping_centers_km,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,mosque_count_1000,price_doc
0,1,43,27.0,4.0,Bibirevo,5001.0,5,11065.0,5,0,240.0,1,0,7,3,0,16,1,no,no,no,2.590241,1.131260,13.575119,1.131260,0.145700,0.177975,2.158587,0.600973,1.080934,5.419893,65.038716,0.274985,3.299822,1.422391,10.918587,13.100618,13.675657,15.156211,no,10.814172,1.676258,0.485841,3.065047,1.107594,8.148591,3.516513,2.392353,6.715026,0.884350,0.648488,0.637189,0.947962,0.177975,0.625783,0.628187,14.053047,7.389498,good,0,5850000
1,2,34,19.0,3.0,Nagatinskij Zaton,3119.0,5,6237.0,8,0,229.0,1,0,6,1,1,3,0,no,no,no,0.936700,0.647337,7.620630,0.635053,0.147754,0.273345,0.550690,0.065321,0.966479,3.411993,40.943917,0.065263,0.783160,9.503405,3.103996,6.444333,8.132640,8.698054,no,6.910568,3.424716,0.668364,2.000154,8.972823,6.127073,1.161579,2.543747,1.852560,0.686252,0.519311,0.688796,1.072315,0.273345,0.967821,0.471447,6.829889,0.709260,excellent,0,6000000
2,3,43,29.0,2.0,Tekstil'shhiki,1463.0,4,5580.0,7,0,1183.0,1,0,5,1,0,0,1,no,no,no,2.120999,1.637996,17.351515,1.445960,0.049102,0.158072,0.374848,0.453172,0.939275,1.277658,15.331896,0.328756,3.945073,5.604800,2.927487,6.963403,8.054252,9.067885,no,5.752368,1.375443,0.733101,1.239304,1.978517,0.767569,1.952771,0.621357,0.841254,1.510089,1.486533,1.543049,0.391957,0.158072,3.178751,0.755946,4.273200,3.156423,poor,0,5700000
3,4,89,50.0,9.0,Mitino,6839.0,9,17063.0,10,0,NaN,1,0,17,6,0,11,4,no,no,no,1.489049,0.984537,11.565624,0.963802,0.179441,0.236455,0.078090,0.106125,0.451173,4.291432,51.497190,0.131597,1.579164,2.677824,14.606501,17.457198,18.309433,19.487005,no,27.892717,0.811275,0.623484,1.950317,6.483172,7.385521,4.923843,3.549558,10.903161,0.622272,0.599914,0.934273,0.892674,0.236455,1.031777,1.561505,16.990677,16.041521,good,0,13100000
4,5,77,77.0,4.0,Basmannoe,3240.0,7,7770.0,9,0,562.0,4,2,25,2,0,10,93,no,yes,no,1.257186,0.876620,8.266305,0.688859,0.247901,0.376838,0.258289,0.236214,0.392871,0.853960,10.247521,0.071480,0.857764,11.616653,1.721834,0.046810,0.787593,2.578671,no,9.155057,1.969738,0.220288,2.544696,3.975401,3.610754,0.307915,1.864637,0.991683,0.892668,0.429052,0.077901,0.810801,0.376838,0.378756,0.121681,1.112486,1.800125,excellent,0,16331452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30466,30469,44,27.0,7.0,Otradnoe,5088.0,4,12721.0,4,0,NaN,1,0,10,3,0,9,6,no,no,no,1.384021,0.659002,8.158093,0.679841,0.132645,0.349899,1.972527,0.139814,0.702853,3.147161,37.765933,0.093258,1.119101,3.762408,8.361875,10.543724,11.118577,12.599292,no,8.820934,0.812253,0.063432,2.190217,0.720736,6.769773,3.470281,3.817988,2.236806,1.442576,0.325885,1.103579,0.167718,0.349899,1.235066,0.612359,7.482165,4.836787,good,0,7400000
30467,30470,86,59.0,3.0,Tverskoe,1874.0,4,6772.0,4,1,1046.0,3,2,29,16,10,23,141,no,yes,no,1.060577,0.781217,9.374609,0.781217,0.276256,0.362681,1.036452,0.271861,0.473020,0.902227,10.826720,0.090712,1.088544,13.100989,1.238732,1.203215,1.874868,3.269284,no,12.102735,1.825643,0.398831,1.133905,2.896280,2.965732,1.912873,0.951754,0.672662,0.796851,0.540003,0.069986,0.086552,0.362681,0.850385,0.310021,0.778428,1.450108,poor,0,25000000
30468,30471,45,NaN,10.0,Poselenie Vnukovskoe,NaN,0,NaN,0,0,NaN,0,0,0,0,0,1,0,no,no,no,2.152792,1.722233,20.666800,1.722233,0.897889,1.234235,4.566595,0.427248,0.353642,3.735666,44.827989,0.630014,7.560163,7.123215,17.148737,19.868997,21.038561,21.905792,no,15.546028,6.433794,1.519553,2.521691,2.715850,13.898607,8.355285,7.401423,12.893684,9.479093,1.806570,4.338453,1.339078,1.234235,1.192543,1.186621,13.459593,9.890758,no data,0,6970959
30469,30472,64,32.0,5.0,Obruchevskoe,2372.0,6,6083.0,8,0,3300.0,2,1,11,1,0,4,5,no,no,no,3.377814,2.047312,24.567748,2.047312,0.203020,0.130667,1.772506,0.227547,2.397723,6.895862,82.750340,0.261528,3.138330,2.327138,8.940313,11.752036,12.872535,13.622569,no,2.515959,2.711199,0.412813,0.631280,2.630674,2.374106,2.210500,1.625064,1.982450,2.340429,1.108672,1.204798,1.340017,0.130667,1.644053,0.476021,2.088193,4.119706,satisfactory,0,13500000
30470,30473,43,28.0,1.0,Novogireevo,2215.0,4,5824.0,4,0,1015.0,2,0,7,1,0,5,1,no,no,no,0.584636,0.454650,5.455795,0.454650,0.093619,0.378950,0.848766,0.559699,0.455194,2.037754,24.453053,0.250151,3.001814,1.920884,6.809408,9.675169,10.228634,11.812614,no,14.028112,1.902431,0.819001,2.370789,1.684764,3.641656,0.812511,0.633901,2.731394,3.065101,0.224601,2.108265,0.825811,0.378950,0.480531,0.867332,0.688707,0.127867,poor,0,5600000

## Работа с пропусками